import { db } from "@/config/firebase";
import { UserCredential } from "firebase/auth";
import { doc, getDoc, setDoc } from "firebase/firestore";

export const createNewUserInDb = async (user: UserCredential | undefined) => {
  const newId = user ? user.user.uid : "";

  // Logic to check if this user is new or already exists in our users collection.
  const userRef = doc(db, "users", newId);
  const userSnap = await getDoc(userRef);

  if (userSnap.exists()) {
    return;
  } else {
    try {
      // setDoc will force the new user doc to use a custom Id, which is set to newId, which is the new Id generated by firebase auth, hence synced.
      await setDoc(doc(db, "users", newId), {
        bio: "",
        createdAt: "",
        displayName: "",
        email: user?.user.email,
        followers: [],
        following: [],
        headerImageUrl: "",
        profilePictureUrl: "",
        userName: user?.user.displayName,
      });
    } catch (err) {
      console.error(err);
    }
  }
};
